@controller=auth
@host=http://waena-desa.id/api/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNTc5NTI4ODA3LCJleHAiOjE1Nzk2MTUyMDd9.LhqJZgK-j97rHRGPobBR_RkAFMGPu9azfTMApwwQRs8

####
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "username":"admin@gmail.com",
    "password":"admin"
}

####
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "username":"chanchan@gmail.com",
    "password":"admin"
}


####
POST {{host}}/registrasi HTTP/1.1
Content-Type: application/json

{
    "email":"chanchan@gmail.com",
    "password":"admin",
    "nik":"123456789",
    "nkk":"987654321"
}


##