

@controller=jenispermohonan
@host=http://localhost:3000/api/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZXMiOltudWxsXSwiaWF0IjoxNTgzMTY0MjAxLCJleHAiOjE1ODMyNTA2MDF9.j-oca1l2l0Na4-hl1fXWOOkMwZuA40vLA08r0M6-YPo

####
GET {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####

####
GET {{host}}/1 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####


GET {{host}}/jenis/Tidak Mampu HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

####
Post {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
    "nama": "Surat Pindah",
    "persyaratan":["Ktp","KK", "AKTA Kelahiran"],
    "deskripsi": "Mengepalai Kelurahan"
}

####
PUT {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "nama": "Surat Pindah",
  "persyaratan": [
    "Ktp",
    "AKTA Kelahiran",
    "Apakek"
  ],
  "deskripsi": "Mengepalai Kelurahan",
  "idjenispermohonan": 1
}


####

DELETE {{host}}/3 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}