

@controller=permohonan
@host=http://localhost:3000/api/{{controller}}
##@host=http://waena-desa.id/api/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJvY3BoMjNAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoyNTkyMDAwfQ.FAEHGjMmPnH6cESQfYnQfbS7RmkKnsWY5bTv-izV0_Q
####
GET {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####

####
GET {{host}}/42 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####



####
GET {{host}}/dokumen/2 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####




####  
Post {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
 
{
   "idpenduduk": 1,
  "data": {
    "tujuanpindah": "jakarta selatan",
    "alamatpindah": "jln. siapa yang ingin andah pindahkan"
  },
  "idjenispermohonan": 1,
  "persetujuan":[]
}

####
PUT {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "idpenduduk": 1,
  "data": {
    "tujuanpindah": "jakarta selatan",
    "alamatpindah": "jln. siapa yang ingin andah pindahkan"
  },
  "idjenispermohonan": 1,
  "tanggalpengajuan": "2020-03-03T17:31:05.677Z",
  "permohonan": 1, 
  "persetujuan":[{"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"created":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"created":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"created":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"}]

}

####
GET {{host}}/approve/46 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####

####  
Post {{host}}/back/46 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
 
{
  "idpermohonan": 1,
  "message":"Permohonan Anda Dikembalikan Ke Admin"
}

####  
Post {{host}}/reject/46 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
 
{
  "idpermohonan": 1,
  "message":"Anda Siapa jadi mau melakukan itu"
}

####

DELETE {{host}}/3 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}