

@controller=permohonan
@host=http://localhost:3000/api/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjI1OTIwMDB9.NsRXlw7lAWEymKOBm5sBaHm-kvsRwU4x2ef5xilrxDo

####
GET {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####

####
GET {{host}}/1 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####

####  
Post {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
 
{
   "idpenduduk": 1,
  "data": {
    "tujuanpindah": "jakarta selatan",
    "alamatpindah": "jln. siapa yang ingin andah pindahkan"
  },
  "idjenispermohonan": 1,
  "persetujuan":[{"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"}]
}

####
PUT {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "idpenduduk": 1,
  "data": {
    "tujuanpindah": "jakarta selatan",
    "alamatpindah": "jln. siapa yang ingin andah pindahkan"
  },
  "idjenispermohonan": 1,
  "tanggalpengajuan": "2020-03-03T17:31:05.677Z",
  "permohonan": 1, 
  "persetujuan":[{"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"},
    {"tanggal":"2020-03-04T17:31:05.677Z","oleh":"admin", "status":"disetujui"}]

}



####

DELETE {{host}}/3 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}