angular.module('admin.router', ['ui.router']).config(function ($stateProvider,$urlRouterProvider) {
	$stateProvider
		.state('admin', {
			url: '/admin',
			controller: 'adminHomeController',
			templateUrl: '../client/apps/views/admin/index.html'
		}).state('admin-home', {
            url: '/home',
            parent: 'admin',
			controller: 'adminHomeController',
			templateUrl: '../client/apps/views/admin/home.html'
        }).state('admin-datakepaladesa', {
            url: '/datakepaladesa',
            parent: 'admin',
			controller: 'admindatakepaladesaController',
			templateUrl: '../client/apps/views/admin/datakepaladesa.html'
		}).state('admin-dataumumdesa', {
            url: '/dataumumdesa',
            parent: 'admin',
			controller: 'admindataumumdesaController',
			templateUrl: '../client/apps/views/admin/dataumumdesa.html'
		}).state('admin-suratmenyurat', {
            url: '/suratmenyurat',
            parent: 'admin',
			controller: 'adminsuratpengantarkkController',
			templateUrl: '../client/apps/views/admin/suratpengantarkk.html'
		}).state('admin-suratpengantarktp', {
            url: '/suratpengantarktp',
            parent: 'admin',
			controller: 'adminsuratpengantarktpController',
			templateUrl: '../client/apps/views/admin/suratpengantarktp.html'
		}).state('admin-datapenduduk', {
            url: '/datapenduduk',
            parent: 'admin',
			controller: 'admindatapendudukController',
			templateUrl: '../client/apps/views/admin/datapenduduk.html'
		}).state('admin-inputdatapenduduk', {
            url: '/inputdatapenduduk',
            parent: 'admin',
			controller: 'admindatapendudukController',
			templateUrl: '../client/apps/views/admin/inputdatapenduduk.html'
		}).state('admin-tambahpermohonan', {
            url: '/tambahpermohonan',
            parent: 'admin',
			controller: 'admintambahpermohonanController',
			templateUrl: '../client/apps/views/admin/tambahpermohonan.html'
		}).state('admin-preview', {
            url: '/preview',
            parent: 'admin',
			controller: 'adminpreviewController',
			templateUrl: '../client/apps/views/admin/preview.html'
		}).state('admin-surattidakmampu', {
            url: '/surattidakmampu',
            parent: 'admin',
			controller: 'adminsurattidakmampuController',
			templateUrl: '../client/apps/views/admin/surattidakmampu.html'
		}).state('admin-suratketdomisili', {
            url: '/suratketdomisili',
            parent: 'admin',
			controller: 'adminsuratketdomisiliController',
			templateUrl: '../client/apps/views/admin/suratketdomisili.html'
		}).state('admin-inbox', {
            url: '/inbox',
            parent: 'admin',
			controller: 'admininboxController',
			templateUrl: '../client/apps/views/admin/inbox.html'
		}).state('admin-permohonan', {
            url: '/permohonan',
            parent: 'admin',
			controller: 'adminpermohonanController',
			templateUrl: '../client/apps/views/admin/permohonan.html'
		}).state('admin-pejabat', {
            url: '/pejabat',
            parent: 'admin',
			controller: 'adminpejabatController',
			templateUrl: '../client/apps/views/admin/pejabat.html'
		}).state('admin-suratskck', {
            url: '/suratskck',
            parent: 'admin',
			controller: 'adminsuratskckController',
			templateUrl: '../client/apps/views/admin/suratskck.html'
		}).state('admin-suratpenguasaantanah', {
            url: '/suratpenguasaantanah',
            parent: 'admin',
			controller: 'adminsuratpenguasaantanahController',
			templateUrl: '../client/apps/views/admin/suratpenguasaantanah.html'
		}).state('admin-suratketusaha', {
            url: '/suratketusaha',
            parent: 'admin',
			controller: 'adminsuratketusahaController',
			templateUrl: '../client/apps/views/admin/suratketusaha.html'
		}).state('admin-suratbelummenikah', {
            url: '/suratbelummenikah',
            parent: 'admin',
			controller: 'adminsuratbelummenikahController',
			templateUrl: '../client/apps/views/admin/suratbelummenikah.html'
		}).state('admin-suratketmenikah', {
            url: '/suratketmenikah',
            parent: 'admin',
			controller: 'adminsuratketmenikahController',
			templateUrl: '../client/apps/views/admin/suratketmenikah.html'
		}).state('admin-suratkelahiran', {
            url: '/suratkelahiran',
            parent: 'admin',
			controller: 'adminsuratkelahiranController',
			templateUrl: '../client/apps/views/admin/suratkelahiran.html'
		}).state('admin-suratketcerai', {
            url: '/suratketcerai',
            parent: 'admin',
			controller: 'adminsuratketceraiController',
			templateUrl: '../client/apps/views/admin/suratketcerai.html'
		}).state('admin-suratketdesa', {
            url: '/suratketdesa',
            parent: 'admin',
			controller: 'adminsuratketdesaController',
			templateUrl: '../client/apps/views/admin/suratketdesa.html'
		}).state('admin-suratketektp', {
            url: '/suratketektp',
            parent: 'admin',
			controller: 'adminsuratketektpController',
			templateUrl: '../client/apps/views/admin/suratketektp.html'
		}).state('admin-suratketlainnya', {
            url: '/suratketlainnya',
            parent: 'admin',
			controller: 'adminsuratketlainnyaController',
			templateUrl: '../client/apps/views/admin/suratketlainnya.html'
		}).state('admin-suratketnikah', {
            url: '/suratketnikah',
            parent: 'admin',
			controller: 'adminsuratketnikahController',
			templateUrl: '../client/apps/views/admin/suratketnikah.html'
		});
		
});
