angular.module('approved.router', ['ui.router']).config(function ($stateProvider, $urlRouterProvider) {
	$stateProvider
		.state('admin-suratpengantarktpApproved', {
			url: '/suratpengantarktp/:id',
			parent: 'admin',
			controller: 'adminsuratpengantarktpController',
			templateUrl: 'apps/views/admin/suratpengantarktp.html'
		}).state('admin-datapendudukApproved', {
			url: '/datapenduduk',
			parent: 'admin',
			controller: 'admindatapendudukController',
			templateUrl: 'apps/views/admin/datapenduduk.html'
		}).state('approved-surattidakmampu', {
			url: '/surattidakmampu/:id',
			parent: 'admin',
			controller: 'approvedSuratTidakMampuController',
			templateUrl: 'apps/views/approved/surattidakmampu.html'
		}).state('admin-suratketdomisiliApproved', {
			url: '/suratketdomisili',
			parent: 'admin',
			controller: 'adminsuratketdomisiliController',
			templateUrl: 'apps/views/admin/suratketdomisili.html'
		}).state('admin-suratskckApproved', {
			url: '/suratskck',
			parent: 'admin',
			controller: 'adminsuratskckController',
			templateUrl: 'apps/views/admin/suratskck.html'
		}).state('admin-suratpenguasaantanahApproved', {
			url: '/suratpenguasaantanah',
			parent: 'admin',
			controller: 'adminsuratpenguasaantanahController',
			templateUrl: 'apps/views/admin/suratpenguasaantanah.html'
		}).state('admin-suratketusahaApproved', {
			url: '/suratketusaha',
			parent: 'admin',
			controller: 'adminsuratketusahaController',
			templateUrl: 'apps/views/admin/suratketusaha.html'
		}).state('approved-suratbelummenikah', {
			url: '/suratbelummenikah/:id',
			parent: 'admin',
			controller: 'approvedSuratBelumMenikahController',
			templateUrl: 'apps/views/approved/suratbelummenikah.html'
		}).state('admin-suratketmenikahApproved', {
			url: '/suratketmenikah',
			parent: 'admin',
			controller: 'adminsuratketmenikahController',
			templateUrl: 'apps/views/admin/suratketmenikah.html'
		}).state('approved-suratkelahiran', {
			url: '/suratkelahiran/:id',
			parent: 'admin',
			controller: 'approvedSuratKelahiranController',
			templateUrl: 'apps/views/approved/suratkelahiran.html'
		}).state('admin-suratketceraiApproved', {
			url: '/suratketcerai',
			parent: 'admin',
			controller: 'adminsuratketceraiController',
			templateUrl: 'apps/views/admin/suratketcerai.html'
		}).state('admin-suratketdesaApproved', {
			url: '/suratketdesa',
			parent: 'admin',
			controller: 'adminsuratketdesaController',
			templateUrl: 'apps/views/admin/suratketdesa.html'
		}).state('admin-suratketektpApproved', {
			url: '/suratketektp',
			parent: 'admin',
			controller: 'adminsuratketektpController',
			templateUrl: 'apps/views/admin/suratketektp.html'
		}).state('admin-suratketlainnyaApproved', {
			url: '/suratketlainnya',
			parent: 'admin',
			controller: 'adminsuratketlainnyaController',
			templateUrl: 'apps/views/admin/suratketlainnya.html'
		}).state('admin-suratketnikahApproved', {
			url: '/suratketnikah',
			parent: 'admin',
			controller: 'adminsuratketnikahController',
			templateUrl: 'apps/views/admin/suratketnikah.html'
		});
});