angular.module('lurah.router', ['ui.router']).config(function ($stateProvider, $urlRouterProvider) {
    $stateProvider
        .state('lurah', {
            url: '/lurah',
            controller: 'lurahController',
            templateUrl: 'apps/views/lurah/index.html'
        }).state('lurah-home', {
            url: '/home',
            parent: 'lurah',
            controller: 'lurahHomeController',
            templateUrl: 'apps/views/lurah/home.html'
        })

        .state('lurah-datakepaladesa', {
            url: '/datakepaladesa',
            parent: 'lurah',
            controller: 'admindatakepaladesaController',
            templateUrl: 'apps/views/admin/datakepaladesa.html'
        }).state('lurah-dataumumdesa', {
            url: '/dataumumdesa',
            parent: 'lurah',
            controller: 'admindataumumdesaController',
            templateUrl: 'apps/views/admin/dataumumdesa.html'
        }).state('lurah-jenispermohonan', {
            url: '/jenispermohonan',
            parent: 'lurah',
            controller: 'adminJenisPermohonanController',
            templateUrl: 'apps/views/admin/jenisPermohonan.html'
        }).state('lurah-suratpengantarktp', {
            url: '/suratpengantarktp',
            parent: 'lurah-surat',
            controller: 'adminsuratpengantarktpController',
            templateUrl: 'apps/views/admin/suratpengantarktp.html'
        }).state('lurah-datapenduduk', {
            url: '/datapenduduk',
            parent: 'lurah',
            controller: 'admindatapendudukController',
            templateUrl: 'apps/views/admin/datapenduduk.html'
        }).state('lurah-inputdatapenduduk', {
            url: '/inputdatapenduduk',
            parent: 'lurah',
            controller: 'admindatapendudukController',
            templateUrl: 'apps/views/admin/inputdatapenduduk.html'
        }).state('lurah-tambahpermohonan', {
            url: '/tambahpermohonan',
            parent: 'lurah',
            controller: 'admintambahpermohonanController',
            templateUrl: 'apps/views/admin/tambahpermohonan.html'
        }).state('lurah-preview', {
            url: '/preview',
            parent: 'lurah',
            controller: 'adminpreviewController',
            templateUrl: 'apps/views/admin/preview.html'
        }).state('lurah-surattidakmampu', {
            url: '/surattidakmampu',
            parent: 'lurah-surat',
            controller: 'adminsurattidakmampuController',
            templateUrl: 'apps/views/admin/surattidakmampu.html'
        }).state('lurah-suratketdomisili', {
            url: '/suratketdomisili',
            parent: 'lurah-surat',
            controller: 'adminsuratketdomisiliController',
            templateUrl: 'apps/views/admin/suratketdomisili.html'
        }).state('lurah-inbox', {
            url: '/inbox',
            parent: 'lurah',
            controller: 'InboxController',
            templateUrl: 'apps/views/inbox.html'
        }).state('lurah-permohonan', {
            url: '/permohonan',
            parent: 'lurah',
            controller: 'adminpermohonanController',
            templateUrl: 'apps/views/admin/permohonan.html'
        }).state('lurah-pejabat', {
            url: '/pejabat',
            parent: 'lurah',
            controller: 'adminpejabatController',
            templateUrl: 'apps/views/admin/pejabat.html'
        }).state('lurah-suratskck', {
            url: '/suratskck',
            parent: 'lurah-surat',
            controller: 'adminsuratskckController',
            templateUrl: 'apps/views/admin/suratskck.html'
        }).state('lurah-suratpenguasaantanah', {
            url: '/suratpenguasaantanah',
            parent: 'lurah-surat',
            controller: 'adminsuratpenguasaantanahController',
            templateUrl: 'apps/views/admin/suratpenguasaantanah.html'
        }).state('lurah-suratketusaha', {
            url: '/suratketusaha',
            parent: 'lurah-surat',
            controller: 'adminsuratketusahaController',
            templateUrl: 'apps/views/admin/suratketusaha.html'
        }).state('lurah-suratbelummenikah', {
            url: '/suratbelummenikah',
            parent: 'lurah-surat',
            controller: 'adminsuratbelummenikahController',
            templateUrl: 'apps/views/admin/suratbelummenikah.html'
        }).state('lurah-suratketmenikah', {
            url: '/suratketmenikah',
            parent: 'lurah-surat',
            controller: 'adminsuratketmenikahController',
            templateUrl: 'apps/views/admin/suratketmenikah.html'
        }).state('lurah-suratkelahiran', {
            url: '/suratkelahiran',
            parent: 'lurah-surat',
            controller: 'adminsuratkelahiranController',
            templateUrl: 'apps/views/admin/suratkelahiran.html'
        }).state('lurah-suratketcerai', {
            url: '/suratketcerai',
            parent: 'lurah-surat',
            controller: 'adminsuratketceraiController',
            templateUrl: 'apps/views/admin/suratketcerai.html'
        }).state('lurah-suratketdesa', {
            url: '/suratketdesa',
            parent: 'lurah-surat',
            controller: 'adminsuratketdesaController',
            templateUrl: 'apps/views/admin/suratketdesa.html'
        }).state('lurah-suratketektp', {
            url: '/suratketektp',
            parent: 'lurah-surat',
            controller: 'adminsuratketektpController',
            templateUrl: 'apps/views/admin/suratketektp.html'
        }).state('lurah-suratketlainnya', {
            url: '/suratketlainnya',
            parent: 'lurah-surat',
            controller: 'adminsuratketlainnyaController',
            templateUrl: 'apps/views/admin/suratketlainnya.html'
        }).state('lurah-suratketnikah', {
            url: '/suratketnikah',
            parent: 'lurah-surat',
            controller: 'adminsuratketnikahController',
            templateUrl: 'apps/views/admin/suratketnikah.html'
        }).state('lurah-suratall', {
			url: '/suratall',
			parent: 'lurah-surat',
			controller: 'adminSuratAllController',
			templateUrl: 'apps/views/admin/suratall.html'
		})
		.state('lurah-surat', {
			url: '/surat',
			parent: 'lurah',
			controller: 'adminSuratController',
			templateUrl: 'apps/views/admin/surat.html'
		});

});